[#chapter-appendix]
Appendix
--------

Some Basic Definitions
~~~~~~~~~~~~~~~~~~~~~~

General Principles
^^^^^^^^^^^^^^^^^^
(Chapters in parentheses discuss principles)

Make friends with yourself (2, 6, 9, 10, 15) +
Accept unconditionally (2, 4, 6, 9, 10, 11, 13, 15) +
Relax (9, 13, 15) +
Be in the here and now (6, 7, 8, 9, 13, 15, 16) +
Have a good time (4, 6, 8, 9, 12, 13, 15) +

Common Traps
^^^^^^^^^^^^
(Chapters in parentheses discuss principles)

Form vs. essence (1, 9, 13, 14, 15) +
Reality vs. mind model (4, 5, 9, 10, 15) +
Person vs. behavior (4, 9, 10, 15) +
More is never enough (9, 10, 13) +

Four Noble Truths (The Buddha)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
. Life is filled with dukkha (suffering/unsatisfactoriness).
. The source of dukkha is craving (Chapter 10).
. Dukkha ends when craving ceases.
. The way to end dukkha and craving is the Eight fold Path.

Eight-Fold Path (The Buddha)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
. Right understanding (Buddhist and equivalent teachings)
. Right thought (no lust, ill-will, or cruelty)
. Right speech (constructive and helpful; no lying, gossip, or vanity)
. Right action (moral, precise, aware)
. Right livelihood (doesn’t cause suffering)
. Right effort (do it; the middle way)
. Right mindfulness (Chapters 8 and 15)
. Right concentration (Chapters 7 and 15)

“Right” = perfect, harmonious, in balance, conscious

Eight Limbs of Yoga (compiled by Patanjali)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
. Yama: abstention from evil conduct
. Niyama: virtuous conduct
. Asana: physical postures
. Pranayama: control of breath and vital energy
. Pratyahara: withdrawal of senses
. Dharana: concentration
. Dhyana: meditation
. Samadhi: union with divine ground

Yama and Niyama (Yoga)
^^^^^^^^^^^^^^^^^^^^^^
* Non-violence
* Non-stealing
* Avoiding sexual excess, control over sexual cravings
* Non-possessiveness, non-hoarding, non-greed
* Truthfulness
* Cleanliness and purity of body and mind
* Practices to perfect body and mind
* Contentment
* Study of self and spiritual works
* Surrender to God/ultimate truth

Five Basic Precepts (Buddhism)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Abstain from:

. Killing
. Stealing
. Inappropriate sexual behavior
. False and/or harmful speech
. Intoxicating or mind-altering drugs, particularly ones causing heedlessness

Ten Commandments (Judaism/Christianity)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
. Have no other gods before the fundamental God
. Do not construct or worship false gods or images of God
. Do not take the name of God in vain
. Do not work on the Sabbath (each seventh day) and keep it holy
. Honor your father and mother
. Do not kill
. Do not commit adultery
. Do not steal
. Do not lie, particularly about others
. Do not covet what is not yours

The Perennial Philosophy (ala Aldous Huxley)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
. The phenomenal world of matter and individualized consciousness, the world of things, animals, people, and gods, is a manifestation of a Divine Ground within which all partial realities have their being, and apart from which they would be nonexistent.
. Humans are capable not merely of knowing about the Divine Ground by inference. They can also realize its existence by a direct intuition which is superior to discursive reasoning. This immediate knowledge unites the knower with what is known.
. People possess a double nature, a phenomenal ego and an eternal Self, the latter being the spirit or spark of divinity within the soul. It is possible for a person to identify with the spirit and therefore the Divine Ground, which is of like nature with the spirit.
. One’s life on earth has only one end and purpose: to identify with the eternal Self and so come to unitive knowledge of the Divine Ground.


Suggested Reading
~~~~~~~~~~~~~~~~~
Many of the books in this list go in and out of print with various publishers. There are also many different translations of some of the non-English books, particularly classic spiritual texts. I cannot say which translation is the most “accurate” or “appropriate” for any particular reader.

The books are grouped by the following overlapping categories: 

American Indians +
Attachments/Addictions +
Autobiographies +
Buddhism and the Buddha +
Buddhism: Tantric/Tibetan +
Buddhism: Zen +
Chakras and Kundalini +
Christian Practice +
Christian Theory +
Consciousness +
Death +
Dreams +
Happiness +
Journals/Diaries +
Judaism +
Love +
Meditation: Practice +
Meditation: Theory and Research +
Mindfulness/Vipassana +
Mysticism/Enlightenment +
References +
Religion +
Religious Classics +
Self-improvement +
Stories +
Sufism +
Taoism +
Teachers: Contemporary +
Transpersonal Psychology: General +
Transpersonal Psychology: East and West +
Yoga: General +
Yoga: Hatha +

American Indians
^^^^^^^^^^^^^^^^
These books deal with the American Indian spiritual perspective, relationship to the Earth, and problems with the white man. Storm tells the philosophy of the Plains people through stories. Freesoul discusses Indian spiritual practices and symbols, including the ceremonial pipe and the medicine wheel. 

- Freesoul, J.R. Breath of the invisible. Quest Books, 1986. 
- McLuhan, T.C. Touch the earth. Outerbridge and Dienstfrey, 1971. 
- Niehardt, J.G. Black Elk speaks. Pocket Books, 1972.
- Storm, H. Seven arrows. Ballantine, 1973.

Attachments/Addictions
^^^^^^^^^^^^^^^^^^^^^^
Goleman surveys the “psychology of self-deception.” Keyes has written many popular books about getting free from attachments. The Mauls’ textbook summarizes many of the barriers to personal growth. 

- Goleman, D. Vital lies, simple truths. Simon & Schuster, 1985. 
- Keyes, K. Handbook to higher consciousness. Living Love Center, fifth edition, 1975. 
- Keyes, K. & P. Keyes. Gathering power through insight and love. Living Love Publications, 1987. 
- Maul, G. & T. Maul. Beyond limit: Ways to growth and freedom. Scott, Foresman, 1983.

Autobiographies
^^^^^^^^^^^^^^^
The personal stories of people involved with pursuing a spiritual path and/or consciousness expansion within the contexts of Christianity (Merton, Roberts), American Indian (Castaneda), Buddhism (HamiltonMerritt, Trungpa, Watts), yoga (Jones, Muktananda, Ram Dass, Swami Rama, Yogananda), psychedelic drugs (Castaneda, Lilly, Ram Dass, Watts), and “other” (Lilly, Merrell-Wolff, Watts). 

- Castaneda, C. The teachings of Don Juan. Ballantine Books, 1969. A separate reality. Simon & Schuster, 1971. Journey to Ixtian. Simon & Schuster, 1972. Tales of power. Simon & Schuster, 1974. 
- Dass, Ram. Be here now. Lama Foundation, 1971. 
- Hamilton-Merritt, J. A meditator’s diary. Pelican Books, 1979. 
- Jones, F. The knee of listening. Dawn Horse Press, 1972. Garbage and the goddess. Dawn Horse Press, 1974. (Jones later calls himself “Bubba Free John.”) 
- Lilly, J. The center of the cyclone. Bantam Books, 1973. 
- Merrell-Wolff, F. Pathways through to space. Warner Books, 1976. 
- Merton, T. The seven storey mountain. Harcourt Brace Jovanovich, 1948. 
- Muktananda Paramahansa, Swami. The play of consciousness. S.Y.D.A. Foundation, 1974. 
- Rama, Swami. Living with the Himalayan masters. Himalayan International Institute of Yoga Science & Philosophy, 1978. 
- Roberts, B. The experience of no-self. Shambhala, 1984. 
- Trungpa, Chbgyam. Born in Tibet. Random House, 1985. 
- Watts, A. In my own way. Vintage Books, 1972. 
- Yogananda, Paramahansa. Autobiography of a Yogi. Self-Realization Fellowship, 1946.

Buddhism and the Buddha
^^^^^^^^^^^^^^^^^^^^^^^
Rahula provides a good introduction to the Buddha and his teachings. Rice and Woodward provide some of the Buddha’s teachings. Byles tells a story of the Buddha’s life and teachings as it might be seen through a disciple’s eyes. Conze and Ross overview some of the development and different schools of Buddhism, and the other three books are compilations of some of the vast Buddhist literature. 

- Burtt, E.A. The teachings of the compassionate Buddha. Mentor, 1955. 
- Byles, M.B. Footprints of Gautama the Buddha. Quest Books, 1967. 
- Conze, E. Buddhism: Its essence and development. Harper Colophon, 1975. 
- Conze, E. & I.B. Horner, D. Sneligrove, & A. Waley. Bud dhist texts through the ages. Harper Torchbooks, 1954. 
- Rahula, W. What the Buddha taught. Grove Press, enlarged edition, 1974. 
- Rice, S. The Buddha speaks here and now. Buddhist Publication Society, 1981. (Buddhist scriptures in contemporary idiom.) 
- Ross, N.W. Buddhism: A way of life and thought. Vintage Books, 1981. 
- Stryk, L. World of the Buddha. Grove Press, 1968. 
- Woodward, F.L. Some sayings of the Buddha. Oxford University Press, 1973.

Buddhism: Tantric/Tibetan
^^^^^^^^^^^^^^^^^^^^^^^^^
The book by Blofeld and the one by Guenther & Tmungpa provide an introductory overview. Chögyam Trungpa, who died recently, and Tarthang Tulku, Tibetan Buddhists, have taught in the United States. The book by Guenther and the one by Hopkins are more academically philosophical and psychological. 

- Blofeld, J. The tantric mysticism of Tibet. E.P. Dutton, 1970. 
- Guenther, H.V. Tibetan Buddhism in Western perspective. Dharma Publishing, 1977. 
- Guenther, H.V. & Chögyam Trungpa. The dawn of tantra. Shambhala, 1975. 
- Hopkins, J. The tantric distinction. Wisdom Publications, 1984. 
- Tarthang Tulku. Gesture of balance. Dharma Publishing, 1977. 
- Trungpa, Chögyam. Journey without goal. Prajna Press, 1981. The myth of freedom. Shambhala, 1976. Cutting through spiritual materialism. Shambhala, 1973.

Buddhism: Zen
^^^^^^^^^^^^^
During the 1950s and 1960s many books by Alan Watts and D. T. Suzuki were part of Zen’s strong influx into the West. The books by Watts and Ross describe the Zen perspective and its influence. Kapleau and Sekida discuss Zen practice. And Suzuki’s (not D. T. Suzuki) book is an excellent set of talks on Zen meditation and attitude. See also “Stories” category. 

- Kapleau, P. The three pillars of Zen. Anchor Books, expanded edition, 1980. 
- Ross, N.W. The world of Zen: An East-West anthology. Vintage Books, 1960. 
- Sekida, K. Zen training. Weatherhill, 1975.
- Suzuki, S. Zen mind, beginners mind. Weatherhill, 1970. 
- Watts, A.W. The way of Zen. Vintage Books, 1957.

Chakras and Kundalini
^^^^^^^^^^^^^^^^^^^^^
Sannella describes some of the psychological problems associated with and/or confused with the rising of kundalini. The other books go further into the chakras and kundalini. 

- Motoyama, H. Theories of the chakras: Bridge to higher consciousness. Quest Books, 1981. 
- Pandit, M.P. Kundalini yoga. Ganesh & Co., 1968.
- Sannella, L. Kundalini —Psychosis or transcendence? H. S. Dakin, 1976. 
- Scott, M. Kundalini in the physical world. Routledge & Kegan Paul, 1983.

Christian Practice
^^^^^^^^^^^^^^^^^^
The books by French, Brother Lawrence, Bunyan, and a Kempis are classics in Christian living and practices, with the originals respectively over 100, 300, 300, and 400 years old. The books by French and Brother Lawrence are concerned with the practice of continual prayer, as mentioned in Chapter 15. Powell discusses the role of attitudes in Christian practice. The three-volume Course in Miracles was “dictated” to psychologist Helen Schucman by a “voice” claiming to be Jesus. These popular books encourage forgiveness and changes in attitudes and thoughts. See also the categories “Meditation: Practice” and “Journals/ Diaries.” 

- A course in miracles. Foundation for Inner Peace, 1975. 
- Bunyan, J. Pilgrim’s progress. Zondervan Publishing House, 1967. 
- French, R.M. (trans.). The way of the pilgrim. Ballantine Books, 1974. 
- Lawrence, Brother. The practice of the presence of God. Whitaker House, 1982. 
- Powell, J. The Christian vision. Argus Communications, 1984. 
- Thomas a Kempis. The imitation of Christ. Image Books, 1985 (Editor: H. C. Gardiner).

Christian Theory
^^^^^^^^^^^^^^^^
To best understand the Bible it is useful to have a handbook, such as Eerdmans’, to provide additional information, such as historical and cultural factors. Since what is included in the Bible was heavily influenced by social and political forces, to better understand early Christianity and the potential breadth of Christianity, it is helpful to consider early Christian writings which were not included. The current best example is the gnostic gospels found at Nag Hammadi. Pagels discusses these gospels, which are given in total by Robinson.

Lewis is currently one of the most popular traditional Christian writers. Jesuit paleontologist Teilhard de Chardin provides a provocative theory of the biological/spiritual evolution of man, which continues well beyond where we are now. Fox argues for a creation- centered Christian spirituality, as opposed to the dominant fall-redemption approach. Swami Prabhavananda discusses the Sermon on the Mount from a Hindu/ yogic point of view. 

- Alexander, D. & P. Alexander (eds.). Eerdmans’ concise Bible handbook. Wm. B. Eerdmans, 1980. 
- Fox, M. Original blessing. Bear & Co., 1983. 
- Lewis, C.S. Mere Christianity. Macmillan, 1943. 
- Pagels, E. The gnostic gospels. Vintage Books, 1981. 
- Prabhavananda, Swami. The Sermon on the Mount ac cording to Vedanta. Mentor Book, 1972. 
- Robinson, J.M. (ed.). The Nag Hammadi library. Harper & Row, 1981. 
- Teilhard de Chardin, P. The phenomenon of man. Harper Torchbook, 1961.

Consciousness
^^^^^^^^^^^^^
Ornstein (1977), Pelletier, and Tart (1975) synthesize some of our knowledge about consciousness. Lilly summarizes work with isolation tanks, while Masters and Houston summarize what has been learned via psychedelic drugs. The other five books are collections of articles about consciousness. 

- Goleman, D. & R.J. Davidson (eds.). Consciousness: Brain, states of awareness, and mysticism. Harper & Row, 1979. 
- Lilly, J.C. The deep self. Warner Books, 1978. 
- Masters, R.E.L. & J. Houston. The varieties of psychedelic experience. Delta Book, 1966. 
- Ornstein, R.E. (ed.). The nature of human consciousness. W. H. Freeman, 1973. 
- Ornstein, R.E. The psychology of consciousness. Harcourt Brace Jovanovich, second edition, 1977. 
- Pelletier, K.R. Toward a science of consciousness. Delta Book, 1978. 
- Tart, C.T. (ed.). Altered states of consciousness. Wiley, 1969. 
- Tart, C.T. States of consciousness. E. P. Dutton, 1975. 
- White, J. (ed.). The highest state of consciousness. Anchor Books, 1972. 
- Wolman, B.B. & M. Ullmann (eds.). Handbook of states of consciousness. Van Nostrand Reinhold, 1986.

Death
^^^^^
Kubler-Ross discusses the psychological needs of the dying person. Levine considers how to die consciously, a spiritual approach to death. Moody surveys the experiences of people who almost died, some of whom were “clinically dead.” 

- Kubler-Ross, E. On death and dying. Macmillan, 1970. 
- Levine, S. Who dies? Anchor Books, 1982. 
- Moody, R.A. Life after life. Bantam Book, 1976.

Dreams
^^^^^^
Faraday discusses how to interpret dreams, Garfield how to plan and work with dreaming, and LaBerge how to “awake” while dreaming. 

- Faraday, A. The dream game. Perennial Library, 1976. 
- Garfield, P. Creative dreaming. Ballantine Books, 1976. 
- LaBerge, S. Lucid dreaming. Ballantine Books, 1986.

Happiness
^^^^^^^^^
These books offer various ideas about how to cultivate happiness, including unconditional acceptance(Kaufman), reducing worry (Carnegie), Western perspectives (Houston), and Eastern perspectives (Watts). 

- Carnegie, D. How to stop worrying and start living. Pocket Book, 1953. 
- Houston, J.P. The pursuit of happiness. Scott Foresman, 1981. 
- Kaufman, B.N. To love is to be happy with. Fawcett Crest, 1977. 
- Watts, A.W. The meaning of happiness. Harper Colophon, 1979.

Journals / Diaries
^^^^^^^^^^^^^^^^^^
Progoff describes how to use his “intensive journal” for personal and transpersonal growth. It is a structured journal with many components and exercises. Rainer shows how to use a journal for “self-guidance and expanded creativity.” Kelsey covers “Christian growth through personal journal writing.” 

- Kelsey, M. Adventure inward. Augsburg Publishing House, 1980. 
- Progoff, I. At a journal workshop. Dialogue House Library, 1975. 
- Rainer, T. The new diary. J. P. Tarcher, 1978.

Judaism
^^^^^^^
Williams provides a history of the Jewish people from 538 B.C. to 1500 A.D. Buber’s book is a classic work in Hasidism, a movement of Jewish mysticism. Hoffman and Schachter pursue the intersection of Hasidism with contemporary psychology. The other books discuss the Kabbalah, a symbolic system of Jewish mysticism and occultism.

- Buber, M. I and thou. Charles Scribner’s Sons, 1970 (Walter Kaufman translator.). 
- Fortune, D. The mystical Qabalah. Ernest Benn, 1935. 
- Gonzalez-Wippler, M. A Kabbalah for the modern world. Bantam Book, 1977. 
- Hoffman, E. The way of splendor. Shambhala, 1981. 
- Ponce, C. Kabbalah. Quest Books, 1986. 
- Schachter, Z.M. & E. Hoffman, Sparks of light. Sham bhala, 1983. 
- Waite, A.E. The holy Kabbalah. University Books, 1960. 
- Williams, J.G. Judaism. Quest Books, 1980.

Love
^^^^
Various perspectives on the nature and cultivation of love. 

- Buscaglia, L. Love. Fawcett Crest, 1972. 
- Fromm, G. The art of loving. Harper & Row, 1956. 
- Hendricks, G. Learning to love yourself. Prentice-Hall, 1982. 
- Welwood, J. (ed.). Challenge of the heart. Shambhala, 1985.

Meditation: Practice
^^^^^^^^^^^^^^^^^^^^
Le Shan’s book is a good general introduction to meditation. Ellwood tells the beginner about quieting the mind via meditation. Solé-Leris provides an introduction to the concentration and mindfulness meditation practices of Theravadin Buddhism. Kelsey discusses Christian meditation, while Fleming elaborates on the classic Christian meditations of St. Ignatius. The book by de Mello is a unique blend of Buddhist mindfulness and Christian meditation (e.g., the St. Ignatius exercises). Other books on Buddhist meditation can be found under “Buddhism: Zen” and “Mindfulness/ Vipassana.” 

- de Mello, A. Sadhana: A way to God. Institute of Jesuit Sources, 1978. 
- Ellwood, R. Finding the quiet mind. Quest Books, 1983. 
- Fleming, D.L. The spiritual exercises of St. Ignatius. Institute of Jesuit Sources, 1978. Kelsey, M. The other side of silence. Paulist Press, 1976. 
- Le Shan, L. How to meditate. Bantam Book, 1975.
- Solé-Leris, A. Tranquility and insight. Shambhala, 1986.

Meditation: Theory and Research
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Goleman surveys the many different approaches to meditation within the major world systems. White’s book is a collection of articles on different aspects of meditation. Carrington and Shapiro & Walsh deal with contemporary Western research approaches to meditation. 

- Carrington, P. Freedom in meditation. Anchor Press, 1978. 
- Goleman, D. The varieties of the meditative experience. E. P. Dutton, 1977. 
- Shapiro, D.H. & R.N. Walsh (eds.). Meditation: Classic and contemporary perspectives. Aldine, 1984. 
- White, J. (ed.). What is meditation? Anchor Books, 1974.

Mindfulness/Vipassana
^^^^^^^^^^^^^^^^^^^^^
Books dealing with mindfulness and vipassana based on classic Theravadin Buddhist teachings and practices. Dhiravamsa, Nyanaponika Thera, and Soma Thera overview such approaches. The Visuddhi Magga is an outstanding encyclopedia of Buddhist doctrine and meditation practices compiled by Buddhaghosa about the fifth century A.D. Goldstein’s book is a set of talks and instructions from a meditation retreat. The other books are from respected contemporary Eastern teachers (Mahasi Sayadaw, S. N. Goenka, Achaan Chah). 

- Buddhaghosa. Visuddi Magga (The path of purification). Buddhist Publication Society, 1975. Translator Bhikkhu Nanamoli. 
- Dhiravamsa. The way of non-attachment. Schocken Books, 1977. 
- Goldstein, J. The experience of insight. Shambhala, 1983. 
- Hart, W. The art of living: Vipassana meditation as taught by S. N. Goenka. Harper & Row, 1987. 
- Kornfield, J. & P. Breiter. A still forest pool: The in sight meditation of Achaan Chah. Quest Books, 1985. 
- Sayadaw, Mahasi. Practical insight meditation. Followed by The progress of insight. Buddhist Publication Society, 1980 & 1978. 
- Thera, Nyanaponika. The heart of Buddhist meditation. Rider & Co., 1962. 
- Thera, Soma. The way of mindfulness. Buddhist Publication Society, fourth edition, 1975.

Mysticism/Enlightenment
^^^^^^^^^^^^^^^^^^^^^^^
White’s book is a good collection of articles about enlightenment. Stace provides a collection of writings from the great mystics of various traditions. Roberts is a contemporary American Christian mystic. MerrellWolff describes a philosophical model of the highest level of consciousness. Bucke’s and Underhill’s books are early classics in the field. Related material can be found under the category “consciousness.” 

- Bucke, M. Cosmic consciousness. E. P. Dutton, 1969. 
- Merrell-Wolff, F. The philosophy of consciousness without an object. Julian Press, 1973. 
- Roberts, B. The path to no-self. Shambhala, 1985.
- Stace, W.T. The teachings of the mystics. Mentor Books, 1960. 
- Underhill, E. Mysticism. E. P. Dutton, 1961.
- White, J. (ed.). What is enlightenment? J. P. Tarcher, 1985.

References
^^^^^^^^^^
The dictionaries by Jack and Reese help define spiritual terms. Popenoe’s book is a massive annotated bibliography of the types of books in this suggested reading section. The New Consciousness Sourcebook, previously The Spiritual Community Guide, is a book that comes out every few years listing spiritual groups, training centers, classified ads, etc. Henderson surveys many of the personal and transpersonal growth groups of the 1970s. The last half of Ram Dass’s book is a directory of American retreat centers and places of meditation instruction. 

- Dass, Ram. Journey of awakening: A meditator’s guidebook. Bantam Book, 1978. 
- Henderson, C.W. Awakening. Prentice-Hall, 1975. 
- Jack, A. The new age dictionary. Kanthaka Press, 1976. 
- Khalsa, P.S. (ed.). The new consciousness sourcebook. Spiritual Community Publications. 
- Popenoe, C. Inner development. Yes! Inc., 1979.
- Reese, W.L. Dictionary of philosophy and religion. Humanities Press, 1980.

Religion
^^^^^^^^
Schuon and Smith discuss the fundamental spiritual commonalities of religions, including the perennial philosophy. Wilber relates religion to his general developmental/consciousness model (see “Teachers: Contemporary”). Lilly surveys the many beliefs that people take for God. James’s book is an early classic in the psychology of religion. Stapleton’s science fiction story tells of an evolving God who creates a succession of universes. Spilka, Hood, and Gorsuch provide a current textbook on the psychology of religion. 

- James, W. The varieties of religious experience. Mentor Books, 1958. 
- Lilly, J.C. Simulations of God. Bantam Books, 1976. 
- Schuon, F. The transcendent unity of religions. Quest Books, 1984. 
- Smith, H. Forgotten truth: The primordial tradition. Harper Colophon, 1977. 
- Spilka, B., R.W. Hood, & R.L. Gorsuch. The psychology of religion. Prentice-Hall, 1985. 
- Stapleton, 0. Star maker. Penguin Books, 1972. 
- Wilber, K. A sociable God. Shambhala, 1983.

Religious Classics
^^^^^^^^^^^^^^^^^^
- Bhagavad-Gita. One of the world’s most loved spiritual works. Instruction in yoga within the context of a great epic story. J. Mascaro, Penguin Books, 1962. Swami Prabhavananda, Mentor Books, 1944. Shri Purohit Swami, Vintage Books, 1977. 
- The Dhammapada. Some sayings of the Buddha. P. Lal, Farrar, Straus & Giroux, 1967. T. Byrom, Vin tage Books, 1976. 
- Holy Bible. The basic text of the Judeo-Christian religions. A collection of folklore, history, letters, laws, ceremonies, hymns, prayers, sermons, odes, proverbs, and essays. The King James version is still preferred by many, though the Revised Standard Version is widely used in theological studies. The gospel of John is perhaps the gospel closest to the perennial philosophy; it is the most “mystical” of the gospels. 
- The Koran (Quran). The holy scripture of Islam, the record of Mohammed’s oral teachings. J. M. Rodwell, translator, Everyman’s Library, 1974. 
- Tao Teh Ching (The way of life). The basic scripture of Taoism attributed to Lao Tzu. R. B. Blakney, Mentor Books, 1955. W. Bynner, Capricorn Books, 1944. G. Feng & J. English, Vintage Books, 1972.

Self-Improvement
^^^^^^^^^^^^^^^^
Books for “cleaning house” (Chapter 11), dealing with common practical psychological problems. 

- Martin, R.A. & Poland, E.Y. Learning to change. McGraw-Hill, 1980. 
- Mikulas, W.L. Skills of living. University Press of America, 1983. 
- Shapiro, D.H. Precision Nirvana. Prentice-Hall, 1978.
- Watson, D.L. & R.G. Tharp. Self-directed behavior. Brooks/Cole, fourth edition, 1985. 
- Williams, R.L. & J.D. Long. Toward a self-managed life style. Houghton Mifflin, third edition, 1983. 
- Yates, B.T. Self-management. Wadsworth, 1985.

Stories
^^^^^^^
These books are all collections of short stories intended to stimulate spiritual understanding. Jataka stories are legends of former lives of the Buddha, often as an animal. Shah’s book is a collection of Sufi stories. 

- de Mello, A. The song of the bird. Image Books, 1984. Kahn, N.I. Twenty Jataka tales. Inner Traditions Inter national, 1985. 
- Reps, P. Zen flesh, Zen bones. Anchor Books, 1957. Salajan, I. Zen comics. Charles E. Tuttle, I in 1974, II in 1982. 
- Shah, I. The pleasantries of the incredible Mulla Nasrudin. E. P. Dutton, 1971. (The first of four such collections.). 
- Van Over, R. Taoist tales. Mentor, 1973.

Sufism
^^^^^^
Books about Sufism, the mystical side of Islam. 

- Lings, M. What is sufism? University of California Press, 1977. 
- Schuon, F. Sufism: Veil and quintessence. World Wis dom Books, 1981. 
- Shah, I. The Sufis. Anchor Books, 1971.

Taoism
^^^^^^
The basic work here is the Tao Teh Ching (see “Religious Classics”) followed by Chuang Tsu ‘s Inner Chapters. Wei’s translation and commentary on the Tao Teh Ching is in terms of meditation and mysticism. 

- Blofeld, J. Gateway to wisdom. Shambhala, 1980. (Taoist and Mahayana Buddhist practices). 
- Blofeld, J. Taoism: The road to immortality. Shambhala,1978. 
- Feng, G. & J. English (translators). Chuang Tsu Inner Chapters. Vintage Books, 1974. 
- Watts, A. Tao: The watercourse way. Pantheon Books, 1975. 
- Wei, H. The guiding light of Lao Tzu. Quest Books, 1982.

Teachers: Contemporary
^^^^^^^^^^^^^^^^^^^^^^
Below is a sample of books from teachers who have been influential in American spirituality in the last twenty-five years. Da Free John (a.k.a. Franklin Jones, Bubba Free John, Da Love-Ananda) is an American teacher who offers himself as a fully realized master. Krishnamurti was a highly respected teacher who encouraged mindfulness and getting free from the search. Merton was a Christian contemplative who incorporated many Eastern perspectives. Ram Dass (Richard Alpert) is a popular and eclectic American bhakti yogi. Watts was a very popular and readable explainer of Eastern perspectives. All have autobiographies listed in that category, except Krishnamurti for whom Mary Lutyens and Pupul Jayakar have written biographies.

Contemporary Buddhist teachers can be found under the Tantric/Tibetan, Zen, and Mindfulness/Vipassana categories. Contemporary yoga teachers include Sri Nisargadatta Maharaj, Swami Muktananda, Swami Narayanda, Swami Rama, and Swami Satchidananda. 

- Da Free John. The Dawn Horse testament of Heart- Master Da Free John. Dawn Horse Press, 1985. 
- Dass, Ram. The only dance there is. Anchor Books, 1974. 
- Dass, Ram. Grist for the mill. Bantam Books, 1979. 
- Krishnamurti, J. The first and last freedom. Harper & Row, 1954. 
- Krishnamurti, J. Think on these things. Harper & Row, 1964. 
- Krishnamurti, J. The second Penguin Krishnamurti reader. Penguin Books, 1970 (M. Lutyens, editor). 
- Krishnamurti, J. The awakening of intelligence. Harper & Row, 1973. 
- Krishnamurti, J. The flame of attention. Harper & Row, 1984. 
- Merton, T. No man is an island. Harcourt, Brace Jovanovich, 1955. 
- Merton, T. Mystics and Zen masters. Delta Book, 1961. 
- Merton, T. A Thomas Merton reader. Image Book, 1974. (T. P. McDonnell, editor). 
- Watts, A.W. The book. Collier Books, 1966. 
- Watts, A.W. Cloud-hidden, whereabouts unknown. Vintage Books, 1974. 
- Watts, A.W. The essence of Alan Watts. Celestial Arts, 1977.

Transpersonal Psychology: General
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Maslow and Van Dusen wrote two of the earlier books in Western transpersonal psychology. Assagioli’s psychosynthesis was one of the first Western psycho- therapies to give significant weight to the transpersonal. Ferrucci gives many exercises within the psychosynthesis tradition. Metzner surveys many of the models/analogies of human growth and transformation. Wilber is one of the foremost contemporary theorists in transpersonal psychology. Ram Dass and Gorman present stories and discussion of people in the helping professions and related personal and spiritual issues. The other books are collections of articles about transpersonal theory and research. 

- Assagioli, R. Psychosynthesis. Penguin Books, 1976. Boorstein, S. (ed.). Transpersonal psychotherapy. Science and Behavior Books, 1980. 
- Dass, Ram & P. Gorman. How can I help? Knopf, 1985.
- Dean, S.R. (ed.). Psychiatry & mysticism. Nelson-Hall, 1975. 
- Ferrucci, P. What we may be. J. P. Tarcher, 1982. 
- Maslow, A. The farther reaches of human nature. Penguin Books, 1976. 
- Metzner, R. Opening to inner light. J. P.Tarcher, 1986.
- Tart, C. T. (ed.). Transpersonal psychologies. Harper & Row, 1975. 
- Van Dusen, W. The natural depth in man. Harper & Row, 1972. 
- Walsh, R.N. & F. Vaughan (eds.). Beyond ego. J. P. Tarcher, 1980. 
- Welwood, J. (ed.). The meeting of the ways. Schocken Books, 1979. 
- Wilber, K. The Atman project. Quest Books, 1980. 
- Wilber, K. Up from Eden. Shambhala, 1983. 
- Wilber, K. Eye to eye. Anchor Books, 1983 (This book is the best overview by Wilber).

Transpersonal Psychology: East and West
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
These books deal with the interfacing of Western and Eastern psychological/spiritual perspectives. Watts is fairly general, Swami Rama and Swami Ajaya emphasize yoga, and the other three emphasize Buddhism. 

- Ajaya, Swami. Psychotherapy East and West. Himalayan Publishers, 1983. 
- Fromm, E., D.T. Suzuki & R. DeMartino. Zen Buddhism and psychoanalysis. Harper & Row, 1960. 
- Katz, N. (ed.). Buddhist and Western psychology. Pra jna Press, 1983. 
- Rama, Swami, R. Ballentine, & Swami Ajaya. Yoga and psychotherapy. Himalayan Institute, 1976. 
- Spiegelman, J.M. & M. Miyuki. Buddhism and Jungiafl psychology. Falcon Press, 1985. 
- Watts, A.W. Psychotherapy East and West. Ballantine Books, 1969.

Yoga: General
^^^^^^^^^^^^^
The books by Eliade, by Prabhavananda and Isher wood (1969), and by Taimni deal with yoga in general and the work of Patanjali. The books by Swami Rama and Wood describe some of the different paths of yoga (see Chapter 13). The other three books introduce three classic yogis, Aurobindo, Ramana Maharshi, and Shankara. See also the category “Chakras and Kundalini.” 

- Eliade, M. Patanjali and yoga. Schocken Books, 1975. 
- Eliade, M. Yoga: Immortality and freedom. Princeton University Press, second edition, 1970. 
- Maharshi, Ramana. The spiritual teaching of Ramana Maharshi. Shambhala, 1972. 
- McDermott, R. The essential Aurobindo. Schocken Books, 1973. 
- Prabhavananda, Swami & C. Isherwood. How to know God: The yoga aphorisms of Patanjali. Mentor, 1969. 
- Prabhavananda, Swami. Shankara‘s crest-jewel of discrimination. Mentor Books, 1970. 
- Rama, Swami. Choosing a path. Himalayan Publishers, 1982. 
- Taimni, I.K. The science of yoga. Quest Books, 1967.
- Wood, E. Seven schools of yoga. Quest Books, 1973.

Yoga: Hatha
^^^^^^^^^^^
Books on hatha yoga including the postures (asanas) and working with the breath and vital energy (pranayama). 

- Hittleman, R. Introduction to yoga. Bantam Books, 1969. 
- Iyengar, B.K.S. Light on yoga. Schocken Books, revised edition, 1977. 
- Iyengar, B.K.S. The concise light on yoga. Schocken Books,1982. 
- Narayanananda, Swami. The secrets of prana, pranayama, and yoga-asanas. N.U. Yoga Trust, 5th edition, 1979. 
- Samskrti & Veda. Hatha yoga. Himalayan Institute, second edition, 1987 (first of two manuals). 
- Rama, Swami. Path of fire and light: Advanced practices of yoga. Himalayan Publishers, 1986. 
- Rama, Swami, R. Ballentine, & A. Hymes. Science of breath. Himalayan Institute, 1979. 
- Vishnudevananda, Swami. The complete illustrated book of yoga. Pocket Book, 1972.
